import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(
    page_title="ECERC Emotion AI",
    page_icon="🧠",
    layout="wide"
)

EMOTIONS = ["Anger", "Disgust", "Sadness", "Joy",
            "Neutral", "Surprise", "Fear"]

st.markdown("""
# 🧠 ECERC Emotion AI
### Evidence-Cause Attention Network for Multi-Modal Emotion Recognition
""")

st.info(
    "This dashboard is ready for demonstration. Connect the trained "
    "checkpoint and preprocessing pipeline for live model inference."
)

tab1, tab2, tab3 = st.tabs(
    ["🎭 Emotion Analysis", "📊 Explainability", "ℹ️ About"]
)

with tab1:
    st.subheader("Conversation")
    text = st.text_area(
        "Enter a conversation",
        value="I can't believe you did that!\nWhat are you talking about?\nYou knew exactly what you were doing."
    )

    if st.button("Analyze Emotion", type="primary"):
        # Demo visualization. Replace with model inference after training.
        probs = np.array([0.72, 0.03, 0.05, 0.05, 0.06, 0.06, 0.03])
        pred = EMOTIONS[int(probs.argmax())]

        c1, c2, c3 = st.columns(3)
        c1.metric("Predicted Emotion", pred)
        c2.metric("Confidence", f"{probs.max()*100:.1f}%")
        c3.metric("Utterances", len([x for x in text.splitlines() if x.strip()]))

        df = pd.DataFrame({"Emotion": EMOTIONS, "Probability": probs})
        fig = px.bar(
            df, x="Emotion", y="Probability",
            title="Emotion Probability Distribution"
        )
        st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Evidence-Cause Explanation")

    modality = pd.DataFrame({
        "Modality": ["Text", "Audio", "Visual"],
        "Contribution": [88, 67, 48]
    })
    fig = px.bar(
        modality, x="Modality", y="Contribution",
        title="Illustrative Modality Contribution"
    )
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("""
    **Interpretation**

    The ECERC architecture is designed to identify emotional evidence in
    the current utterance and relate it to contextual causes from the
    conversation. The values above are demonstration values until a
    trained checkpoint is connected.
    """)

with tab3:
    st.subheader("Project")
    st.write("""
    ECERC is an evidence-cause attention approach for multimodal emotion
    recognition in conversation. The implementation combines text, audio
    and visual representations with gating and attention mechanisms.

    **Research components**
    - Multimodal representation learning
    - Evidence gating
    - Cause encoding
    - Evidence-cause cross attention
    - Feature gating
    - Emotion classification
    - Explainable visualization
    """)

    st.warning(
        "For a final academic submission, replace demonstration values with "
        "results generated by your own trained model."
    )
